---
latitude: 41.88719
longitude: -87.65184
map_zoom: 12
name: Ace Hotel Chicago
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 311 North Morgan Street
  street2: ''
  state: Illinois
  city: Chicago
  country: United States
  zip_code: '60607'
_hotel_id: ACE754
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
